const defaultTheme = require('tailwindcss/defaultTheme');

const CALENDAR_BOX_SHADOW = '0px 26px 100px rgba(104, 150, 82, 0.4)';

/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        './node_modules/@protonemedia/inertiajs-tables-laravel-query-builder/**/*.{js,vue}',
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.{vue,styles.ts}',
    ],
    theme: {
        extend: {
            screens: {
                xxs: '360px',
                xs: '480px',
                mac: '1450px',
                '3xl': '1862px',
            },
            fontFamily: {
                sans: ['Poppins', ...defaultTheme.fontFamily.sans],
                calendarTime: ['Roboto'],
                widgetSecondary: ['Raleway', ...defaultTheme.fontFamily.sans],
                montserrat: ['Montserrat'],
            },
            fontSize: {
                xxxs: '0.5rem',
                xxs: '0.625rem',
                cardHeader: '1.75rem',
                '2.75xl': '1.781rem',
                '3.5xl': '2.063rem',
            },
            opacity: {
                15: '0.15',
            },
            colors: {
                ui: {
                    text: 'rgb(26 35 21 / 0.6)',
                    black: '#1a2315',
                    red: '#c3390d',
                    green: {
                        DEFAULT:
                            'rgb(var(--ui-green-500) / var(--tw-bg-opacity))',
                        50: 'rgb(var(--ui-green-50) / var(--tw-bg-opacity))',
                        100: 'rgb(var(--ui-green-100) / var(--tw-bg-opacity))',
                        200: 'rgb(var(--ui-green-200) / var(--tw-bg-opacity))',
                        300: 'rgb(var(--ui-green-300) / var(--tw-bg-opacity))',
                        400: 'rgb(var(--ui-green-400) / var(--tw-bg-opacity))',
                        500: 'rgb(var(--ui-green-500) / var(--tw-bg-opacity))',
                        600: 'rgb(var(--ui-green-600) / var(--tw-bg-opacity))',
                        700: 'rgb(var(--ui-green-700) / var(--tw-bg-opacity))',
                        800: 'rgb(var(--ui-green-800) / var(--tw-bg-opacity))',
                        900: 'rgb(var(--ui-green-900) / var(--tw-bg-opacity))',
                        950: 'rgb(var(--ui-green-950) / var(--tw-bg-opacity))',
                    },
                },
                'widget-2': {
                    red: '#c93636',
                },
                gray: {
                    1: '#fafafa',
                    2: '#CFCFCF',
                    3: '#9AA1B3',
                    4: '#757b8a',
                    5: '#615F5F',
                    6: '#3E3E3E',
                    7: '#22222F',
                    8: '#1B1B28',
                    9: '#F1F1F1',
                    10: '#f6f6f6',
                    11: '#B1B1B1',
                    12: '#EBEBEB',
                },
                brand: {
                    base: '#1BC5BD',
                    dark: '#0FA7A0',
                    light: 'rgba(27, 197, 189, 0.15)',
                },
                danger: {
                    base: '#F64E4E',
                    dark: '#E23030',
                    light: 'rgba(246, 78, 78, 0.15)',
                },
                warning: {
                    base: '#FFAA07',
                    dark: '#E99C0A',
                    light: 'rgba(255,170,7,0.15)',
                },
                info: {
                    base: '#3699FF',
                    dark: '#1C73CD',
                    light: 'rgba(54, 153, 255,0.15)',
                },
            },
            lineHeight: {
                12: '3rem',
            },
            width: {
                86: '21.5rem',
                33: '8.25rem',
            },
            minWidth: {
                5: '20px',
                6: '24px',
                10: '40px',
                14: '56px',
                64: '256px',
                70: '280px',
                80: '320px',
            },
            minHeight: {
                20: '80px',
                72: '288px',
                150: '600px',
                160: '640px',
            },
            maxWidth: {
                auth: '562px',
                calendar: '1236px',
                30: '120px',
                53: '212px',
                85: '340px',
                98: '392px',
                104: '414px',
                132: '528px',
                190: '760px',
                228: '912px',
            },
            spacing: {
                0.25: '1px',
                0.75: '3px',
                1.25: '5px',
                2.25: '9px',
                2.75: '11px',
                3.25: '13px',
                3.5: '14px',
                3.75: '15px',
                4.25: '17px',
                4.5: '18px',
                4.75: '19px',
                5.25: '21px',
                5.5: '22px',
                6.5: '26px',
                7.25: '29px',
                7.5: '30px',
                8.25: '33px',
                8.5: '34px',
                9.5: '38px',
                10.5: '42px',
                11: '44px',
                11.5: '46px',
                11.5: '46px',
                12.25: '49px',
                12.5: '50px',
                13: '52px',
                15: '60px',
                16.5: '66px',
                17: '68px',
                18: '72px',
                19: '76px',
                21.5: '86px',
                22: '88px',
                23: '92px',
                23.5: '5.75rem',
                25: '100px',
                28: '112px',
                28.5: '114px',
                29: '116px',
                30: '120px',
                34.5: '138px',
                35: '140px',
                42: '168px',
                46: '184px',
                50: '200px',
                51.5: '206px',
                54: '216px',
                54.5: '218px',
                55: '220px',
                59: '236px',
                66: '264px',
                68.5: '274px',
                69.5: '278px',
                74: '296px',
                87.5: '350px',
                92: '368px',
                100: '400px',
                110: '440px',
                112: '448px',
                136: '544px',
                144: '576px',
                150: '600px',
                156: '624px',
                160: '640px',
                170: '680px',
                175: '700px',
                179: '726px',
                180: '720px',
                228: '912px',
            },
            borderRadius: {
                10: '2.5rem',
                '2.5xl': '1.25rem',
                '4xl': '2rem',
                '4.5xl': '2.25rem',
                '5xl': '2.5rem',
            },
            borderWidth: {
                1.5: '1.5px',
                3: '3px',
            },
            boxShadow: {
                'calendar-carousel-button':
                    '0px 10px 16px 0px rgba(100, 151, 76, 0.3)',
                'calendar-box': CALENDAR_BOX_SHADOW,
                'widget-2-select': '0px 7px 33px -12px rgba(48, 94, 26, 0.56)',
            },
            dropShadow: {
                'calendar-box': CALENDAR_BOX_SHADOW,
            },
            backgroundImage: {
                'calendar-background':
                    "url('@as/images/widget-1/background.svg')",
                'order-summary-border-vertical':
                    'var(--order-summary-border-vertical-source)',
                'order-summary-border-horizontal':
                    'var(--order-summary-border-horizontal-source)',
            },
            backgroundPosition: {
                'right-137.5': 'right 550px',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/typography'),
        require('tailwind-scrollbar')({ nocompatible: true }),
    ],
};
