<?php

return [
	'agreements' => ['type', 'is_filled', 'active', 'required'],
	'discount_codes' => [
		'code',
		'active',
		'type',
		'value',
		'club',
		'game',
		'code_quantity',
		'code_quantity_per_customer',
		'start_at',
		'end_at',
	],
	'special_offers' => [
		'name',
		'game',
		'active',
		'value',
		'active_week_days',
		'duration',
		'slots',
		'time_range',
		'when_applies',
		'when_not_applies',
	],
	'settlements' => ['date', 'amount'],
	'announcements' => ['start_at', 'content'],
	'employees' => ['first_name', 'last_name', 'email', 'last_login', 'type'],
	'opening_hours_exceptions' => ['date_range', 'club_hours', 'reservation_hours'],
	'sets' => ['name', 'active', 'today_all', 'today_sold', 'today_available', 'created_at'],
	'pricelists' => ['name'],
	'invoices' => ['created_at', 'total_gross', 'title'],
	'rates' => [
		'game_name',
		'number',
		'start_datetime',
		'customer_name',
		'customer_phone',
		'customer_email',
		'rate_service',
		'rate_atmosphere',
		'rate_staff',
		'rate_final',
		'rate_content',
	],
	'refunds' => ['customer_name', 'refundable_id', 'created_at', 'price', 'cancelation_type', 'status'],
	'reservation_types' => ['name', 'color'],
	'admin_countries' => ['code', 'name', 'currency', 'active', 'clubs_count'],
	'admin_customers' => ['id', 'club_name', 'full_name', 'email', 'phone'],
	'admin_settlements_clubs' => ['id', 'club_name', 'amount'],
	'admin_clubs' => [
		'id',
		'name',
		'email',
		'city',
		'panel_enabled',
		'widget_enabled',
		'calendar_enabled',
		'aggregator_enabled',
		'created_at',
	],
	'admin_games' => ['id', 'name', 'icon', 'clubs_count'],
	'admin_country_games' => ['name'],
	'admin_help_sections' => ['title', 'weight', 'active'],
	'admin_help_items' => ['video_url', 'title', 'weight', 'active'],
	'admin_help_item_images' => ['id', 'path'],
	'admin_refunds' => ['id', 'club_name', 'reservation_number', 'created_at', 'price'],
	'admin_products' => ['id', 'name_pl', 'name_en'],
	'admin_club_product' => ['id', 'name_pl', 'period', 'cost'],
	'admin_club_commissions' => ['name', 'include_on_invoice_status', 'include_on_invoice', 'commission'],
	'admin_club_sms' => ['name', 'price', 'status', 'commission'],
];
